name: Generate GitHub Stats SVGs

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "jstrieb/github-stats"

      - name: Generate images
        run: |
          pip install --upgrade -r requirements.txt
          python3 generate_images.py
        env:
          GITHUB_ACTOR: faisal-kursheedali
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          EXCLUDED: ""
          EXCLUDED_LANGS: ""
          EXCLUDE_FORKED_REPOS: "false"

      - name: Deploy to images branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_branch: images
          publish_dir: ./generated
          commit_message: "chore: update GitHub stats SVGs"
